branch-defaults:
  master:
    environment: dev-env
    group_suffix: null
global:
  application_name: DropBug
  default_ec2_keyname: aws-eb
  default_platform: Node.js
  default_region: ap-southeast-1
  profile: eb-cli
  sc: git
